apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend:24
  namespace: workshop
  labels:
    role: frontend:24
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend:24
  template:
    metadata:
      labels:
        role: frontend:24
    spec:
      containers:
      - name: frontend:24
        image: kalyan555/frontend:24
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://challange.devopslearning.in/api/tasks" #$API_ELB_PUBLIC_FQDN #add your API_Load_Balancer DNS manually here if app does not run
        ports:
        - containerPort: 3000
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 2
        #   periodSeconds: 5
        # readinessProbe:
        #   httpGet:
        #      path: /
        #      port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   successThreshold: 1
